### ISSUE TITLE
tensorflow-gpu 로 학습하는 방법이 있는지 궁금합니다.

### ISSUE THREAD

**Issue by Choikyungho9** [BEOKS/Bicycle-Helmet-Wearing-Detection#2]
안녕하십니까 구글에서 블로그를 보고 들어오게 되었는데요, 
올려주신 ipynb 파일을 실행해보면서 감지모델을 만들고 있습니다. 
궁금한 점이 있는데, 학습속도가 너무 느립니다. 
혹시 tensorflow-gpu 같은 빠른 속도로 학습을 하고 싶은데 방법을 알고계신지 궁금합니다.

**Comment by BEOKS** [comment]
안녕하세요 늦게 답변드려서 미안합니다.

ipynb에서 train한 경우 이미 gpu를 사용하고 있습니다.
속도가 느린 이유는 3가지 정도로 예상할 수 있을것 같네요
1. num_steps가 100000으로 상당히 많기 때문에 기본적으로 시간이 많이 소요됩니다. ( 하지만 num_steps를 낮추면 성능이 많이 저하될 수 있으므로 추천하지 않습니다.)
2. tensorflow에서 gpu를 못 찾고 있다. ( nvidia 드라이버가 제대로 세팅되어 있지 않아 tensorflow가 gpu를 인식하지 못해 cpu로 대체하여 실행 할 가능성이 있습니다. 노트북 세션중 Train Model 출력창에서 아래와 같은 로그가 있는지 확인해보세요! 없다면 GPU를 찾지 못하는 것입니다.)
```
2021-03-09 02:22:45.277013: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 0 with properties
```
3. 사용하는 GPU기기 성능의 문제(코드를 동작하는데 수행한 GPU세팅은 아래와 같습니다, 성능이 더 낮진 않은지 확인해보세요)
```
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
```

**Comment by Choikyungho9** [comment]
감사합니다. 속도가 아주 많이 개선되지는 않지만, 원인을 알게되었습니다.

**Comment by BEOKS** [comment]
혹시 원인과 개선방법을 알려줄 수 있나요? 중요하다면 레포지토리에 반영하고 싶네요
